config/routes.rb
Rails.application.routes.draw do
  root 'players#index'

  post "/players/remove_group_from_player/:id/:gruppennummer" => "players#remove_group_from_player"
  post "/players/add_player_to_group/:id/:gruppennummer" => "players#add_player_to_group"
  post "/players/show_results_in_group/:gruppennummer" => "players#show_results_in_group"
  post "/players/update_set_in_match/:matchid/:setnummer/:ballanzahl" => "players#update_set_in_match"
  post "/players/update_set_in_match/:matchid/:setnummer" => "players#update_set_in_match"
  post "/players/erzeuge_player/:player" => "players#erzeuge_player"

  resources :players


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

 end

app/models/player.rb
class Player < ApplicationRecord
end

app/controllers/players_controller.rb
class PlayersController < ActionController::Base
    def index
        puts "def index..."
        @players = Player.all.reverse_order
        @players_in_gruppe1_with_results = Hash.new
        @players_in_gruppe2_with_results = Hash.new
        @players_in_gruppe3_with_results = Hash.new
        @players_in_gruppe4_with_results = Hash.new

        @players_in_gruppe1_with_results = berechne_gruppen_ranking("1")
        @players_in_gruppe2_with_results = berechne_gruppen_ranking("2")
        @players_in_gruppe3_with_results = berechne_gruppen_ranking("3")
        @players_in_gruppe4_with_results = berechne_gruppen_ranking("4")



        #p @players_in_gruppe3_with_results
    end

    def update_set_in_match
        require 'uri'

        puts "update_set_in_match..."
        puts "matchid: #{params[:matchid]}"
        puts "set: #{params[:setnummer]}"
        puts "ballanzahl: #{params[:ballanzahl]}"
        puts "gruppennummer: #{params[:gruppennummer]}"
        
        if !params[:ballanzahl].blank?
            ballanzahl = URI.escape(params[:ballanzahl])
            puts "ballanzahl: " + ballanzahl
        else
            ballanzahl = nil
            puts "keine Ballanzahl"
        end
        
        match = Match.where(:id => params[:matchid])
        if params[:setnummer] == "1"
            match.update(:set1 => ballanzahl)
        elsif params[:setnummer] == "2"
            match.update(:set2 => ballanzahl)
        elsif params[:setnummer] == "3"
            match.update(:set3 => ballanzahl)
        elsif params[:setnummer] == "4"
            match.update(:set4 => ballanzahl)
        elsif params[:setnummer] == "5"
            match.update(:set5 => ballanzahl)
        end
      

        match = Match.where(:id => params[:matchid]).first
       
        
        @ballverhaeltnis = berechne_ballverhaeltnis(match.set1, match.set2, match.set3, match.set4, match.set5)
        @satzverhaeltnis = berechne_satzverhaeltnis(match.set1, match.set2, match.set3, match.set4, match.set5)
        puts "satzverhaeltnis: #{@satzverhaeltnis.inspect}"
        ########################################################
        if @satzverhaeltnis.to_s =~ /3/ # ein abgeschlossenes Spiel #
            @players_in_gruppe_with_results = Hash.new
            @players_in_gruppe_with_results = berechne_gruppen_ranking(params[:gruppennummer])   #
        end                                                    # 
        #########################################################
        
        respond_to do |format|
            format.js
        end
    end

    def berechne_gruppen_ranking(gruppennummer) # dann in die index-Action hinzufügen
        puts "berechne_gruppen_ranking neu... in Gruppe #{gruppennummer}"
        @players_in_group = Player.where(:gruppennummer => gruppennummer)
        @players_h = Hash.new
     
        @players_id_a = []
        @players_in_group.each do |player| 
            @players_id_a << player.id
            @players_h[player.id.to_s] = player.name 
        end
        puts @players_id_a.inspect
        # für jeden Spieler in der Tabelle matches (Spalten player1_id player2_id) seine Einzelergebnisse nachschlagen und zusammenzählen.
        # Dann das Ranking erstellen und rendern.
        players_results_h = Hash.new
     
        #  Das Gruppenranking wird nur berechnet, wenn mehr als 1 Spieler in der Gruppe ist.
       
        if @players_id_a.size > 1 
            @players_id_a.each do | pl_id |
                puts "kuck for pl_id  #{pl_id} (a)"
                match_plus = 0
                match_minus = 0
                puts "pl_id: #{pl_id}"
                matches_player1 = Match.where(:player1_id => pl_id) 
                p matches_player1
                matches_player1.each do | match |
                puts "match.id: " + match.id.to_s
                    ballverhaeltnis = berechne_ballverhaeltnis(match.set1, match.set2, match.set3, match.set4, match.set5)
                    satzverhaeltnis = berechne_satzverhaeltnis(match.set1, match.set2, match.set3, match.set4, match.set5)
                    

                    if !players_results_h.has_key?(pl_id)
                        if (satzverhaeltnis[0] > satzverhaeltnis[1])
                            match_plus  = match_plus + 1
                        elsif (satzverhaeltnis[0] < satzverhaeltnis[1])

                            match_minus = match_minus + 1
                        end
                        
                        players_results_h[pl_id] = ["match_plus" => match_plus, "match_minus" => match_minus , "name" =>  @players_h[pl_id.to_s], "player_id" => pl_id,  "ball_plus" => ballverhaeltnis[0], "ball_minus" => ballverhaeltnis[1], "satz_plus" => satzverhaeltnis[0], "satz_minus" => satzverhaeltnis[1], "gruppennummer" => gruppennummer ]
                    else
                        players_results_h[pl_id][0]["ball_plus"] = players_results_h[pl_id][0]["ball_plus"] + ballverhaeltnis[0]
                        players_results_h[pl_id][0]["satz_plus"] = players_results_h[pl_id][0]["satz_plus"] + satzverhaeltnis[0]
                        players_results_h[pl_id][0]["ball_minus"] = players_results_h[pl_id][0]["ball_minus"] + ballverhaeltnis[1]
                        players_results_h[pl_id][0]["satz_minus"] = players_results_h[pl_id][0]["satz_minus"] + satzverhaeltnis[1]
                        if (satzverhaeltnis[0] > satzverhaeltnis[1])
                            players_results_h[pl_id][0]["match_plus"] = players_results_h[pl_id][0]["match_plus"] + 1
                        elsif (satzverhaeltnis[0] < satzverhaeltnis[1])
                            players_results_h[pl_id][0]["match_minus"] = players_results_h[pl_id][0]["match_minus"] + 1
                        end
                    end
                end
            
            end

            @players_id_a.each do | pl_id |
                puts "kuck for pl_id  #{pl_id} (b)"
                p players_results_h.inspect
                if !players_results_h[pl_id].nil?
                    match_plus = players_results_h[pl_id][0]["match_plus"]
                    match_minus = players_results_h[pl_id][0]["match_minus"]
                else
                    match_plus = 0
                    match_minus = 0
                end

                matches_player2 = Match.where(:player2_id => pl_id) 
                matches_player2.each do | match |
                    p match
                    ballverhaeltnis = berechne_ballverhaeltnis(match.set1, match.set2, match.set3, match.set4, match.set5)
                    satzverhaeltnis = berechne_satzverhaeltnis(match.set1, match.set2, match.set3, match.set4, match.set5)
                    if (satzverhaeltnis[0] > satzverhaeltnis[1])
                        match_minus = match_minus + 1
                    elsif (satzverhaeltnis[0] < satzverhaeltnis[1])
                        match_plus = match_plus  + 1
                    end

                    
                    if !players_results_h.has_key?(pl_id)
                        players_results_h[pl_id] = ["match_plus" => match_plus, "match_minus" => match_minus , "name" =>  @players_h[pl_id.to_s], "ball_plus" => ballverhaeltnis[1], "ball_minus" => ballverhaeltnis[0], "satz_plus" => satzverhaeltnis[1], "satz_minus" => satzverhaeltnis[0], "gruppennummer" => gruppennummer ]
                    else
                        players_results_h[pl_id][0]["ball_plus"] = players_results_h[pl_id][0]["ball_plus"] + ballverhaeltnis[1]
                        players_results_h[pl_id][0]["satz_plus"] = players_results_h[pl_id][0]["satz_plus"] + satzverhaeltnis[1]
                        players_results_h[pl_id][0]["ball_minus"] = players_results_h[pl_id][0]["ball_minus"] + ballverhaeltnis[0]
                        players_results_h[pl_id][0]["satz_minus"] = players_results_h[pl_id][0]["satz_minus"] + satzverhaeltnis[0]
                        
                        if (satzverhaeltnis[0] > satzverhaeltnis[1])
                            players_results_h[pl_id][0]["match_minus"] = players_results_h[pl_id][0]["match_minus"] + 1
                        elsif (satzverhaeltnis[0] < satzverhaeltnis[1])
                            players_results_h[pl_id][0]["match_plus"] = players_results_h[pl_id][0]["match_plus"] + 1
                        
                        end
                    
                    end
                end
            end
        else # wenn 0 oder 1 Spieler in der Gruppe, dann wird das Ranking nicht berechnet
            # bei 0 Spieler: nichts machen
            # bei 1 Spieler: Diesen Spieler mit Nullwerten rendern.
            if @players_id_a.size == 1
                player_id = @players_id_a[0]
                players_results_h[player_id] = ["match_plus" => 0, "match_minus" => 0 , "name" =>  @players_h[player_id.to_s], "ball_plus" => 0, "ball_minus" => 0, "satz_plus" => 0, "satz_minus" => 0, "gruppennummer" => gruppennummer ]
                  
            else # 0 Spieler
                # nichts machen
            end
        end

       # Dieser Code verwendet sort_by um den Hash zu sortieren. 
       # Wir sortieren zuerst nach "satz_plus" absteigend (daher das negative Vorzeichen)
       # und dann nach "satz_minus" aufsteigend. 
       # Das Ergebnis wird dann in einen Hash zurückgewandelt, 
       # um die ursprüngliche Struktur beizubehalten.

      #  players_results_sorted_satz_h = Hash[players_results_h.sort_by { |key, value| value.first["satz_plus"] }.to_a].reverse_each
         players_results_sorted_h  = players_results_h.sort_by { |key, value| [-value[0]['satz_plus'], value[0]['satz_minus'], -value[0]['ball_plus'], value[0]['ball_minus'] ] }.to_h
        # players_results_h = {18=>[{"match_plus"=>0, "match_minus"=>3, "name"=>"Peter", "matches"=>"1", "ball_plus"=>51, "ball_minus"=>104, "satz_plus"=>0, "satz_minus"=>9, "gruppennummer"=>"2"}], 

app/views/players/_gruppen.html.erb
<div class="col-md-3 border bg-light" id="gr_body_<%= gruppe %>">
    <table id="gruppe_<%= gruppe %>" class="table table-bordered table-sm bg-white mt-2">
    <tr><th>Spieler</th><th>Spiele</th><th>Bälle</th><th>Sätze</th></tr>
  
        <% players.each do |key, value|  %>
            
            <tr id='spieler_<%= key %>' class='tr_spieler'>
         
            <td><%= value[0]["name"] %></td>
            <td><%= value[0]["match_plus"] %>:<%= value[0]["match_minus"] %></td>
            <td><%= value[0]["ball_plus"] %>:<%= value[0]["ball_minus"] %></td>
            <td><%= value[0]["satz_plus"] %>:<%= value[0]["satz_minus"] %></td>
            </tr>
            
        <% end %>
    
    </table>
</div>

app/views/players/add_player_to_group.js.erb
$('#gruppe_<%= params[:gruppennummer] %> .tr_spieler').remove();

<% @players_group.each do | player | %>
    $('#gruppe_<%= params[:gruppennummer] %>').append("\
    <tr class='tr_spieler' id='spieler_<%= player.id %>'>\
        <td><%= player.name %></td>\
    <td>0</td>\
    <td>0:0</td>\
    <td>0:0</td>\
    </tr>\
    ");
<% end %>

 window.location.href="/";

app/views/players/edit.html.erb
<h1>Spieler editieren</h1>
<%= form_for :player,url: "/players/#{@player.id}", method: :patch do |f|%>
    <p>
<%=  "Name" %><br>
<%= f.text_field(:name, size: "10",:maxlength => "10") %>
</p>

 <%= f.submit "Name updaten" %>
<% end %>

app/views/players/index.html.erb
<div class="row">
<div class="col-md-12 text-center"  style="color: #fff;background-color:#C0C0C0;">
<h2>One-Page TT-Tournament von <a href="https://tt-finder.net" target="_blank">tt-finder.net</a></h2>
</div>
</div>

<div id="notice">
</div>

<div class="row mt-2">
<div class="col-md-3 border p-1 text-center" id="gr_header_1">
<h5>Gruppe 1</h5>
</div>
<div class="col-md-3 border  p-1 text-center" id="gr_header_2">
<h5>Gruppe 2</h5>
</div>
<div class="col-md-3 border  p-1 text-center" id="gr_header_3">
<h5>Gruppe 3</h5>
</div>
<div class="col-md-3 border  p-1 text-center" id="gr_header_4">
<h5>Gruppe 4</h5>
</div>
</div>

<div class="row">

<%= render "gruppen", :gruppe => 1, :players => @players_in_gruppe1_with_results %>
<%= render "gruppen", :gruppe => 2, :players => @players_in_gruppe2_with_results %>
<%= render "gruppen", :gruppe => 3, :players => @players_in_gruppe3_with_results %>
<%= render "gruppen", :gruppe => 4, :players => @players_in_gruppe4_with_results %>

</div>

<div class="row mt-2">
    <% ["1","2","3","4"].each do | gruppe | %>
        <div class="col-md-3">
        <%=link_to "Einzelergebnisse Gruppe #{gruppe}", "/players/show_results_in_group/#{gruppe}" , :method => "POST", :remote => true, :class => "btn btn-light", :id=>"btn_einzelergebnisse_#{gruppe}" %>
         <%#=link_to "X", "/players/remove_group_from_player/#{player.id}/#{player.gruppennummer}", :method => "POST", :remote => true, data: { confirm: 'Sicher den Spieler aus der Gruppe entfernen?'}, :class=> "btn btn-sm btn-danger" %>

        </div>
    <% end %>
</div>



<div class="row">
<div class="col-md-12">
<div id="einzelergebnisse_header">
</div>
<table id="einzelergebnisse" class='table '>

</table>
</div>

</div>




<div class="row m-2">
<div class="offset-md-2 col-md-8">

<hr />
<div class="row">
<div class="col-md-6">
<h4>Angemeldete Spieler</h4>
</div>
<div class="col-md-6 text-right">
<input id="newplayer" size="10" maxlength="10">
    <%=link_to "Spieler hinzufügen", "#", :remote => true, :method => "POST", :id => 'erzeuge_player', :class => "btn  btn-dark" %>
</div>
</div>
<hr />
<table class="table table-striped table-sm">
<tr>
<th>
id
</th>
<th>
Spielername
</th>
<th>
Gruppe
</th>
<th>
Action
</th>

</tr>
<% @players.each do |player| %>
<tr>
<td>
   <%= player.id %>
</td>
<td>
    <%= player.name %> 
</td>
<td>
<span id="<%= player.id %>">

<% if !player.gruppennummer.blank? %>
   <% if player.gruppennummer == 1 %>
      <% selected_group1 = "selected" %>
   <% elsif player.gruppennummer == 2 %>
       <% selected_group2 = "selected" %>
    <% elsif player.gruppennummer == 3 %>
       <% selected_group3 = "selected" %>
    <% elsif player.gruppennummer == 4 %>
       <% selected_group4 = "selected" %>
   <% end %>

<select name="gruppe_select"  playerid="<%= player.id %>"  class=" gruppe_select select-option no-scroll text-dark bg-light p-2 rounded  border-0" size="1">
<option value='0'  style="background-color:red;" >keine Gruppe</option>
<option value='1' <%= selected_group1 %>>Gruppe 1</option>
<option value='2' <%= selected_group2 %>>Gruppe 2</option>
<option value='3' <%= selected_group3 %>>Gruppe 3</option>
<option value='4' <%= selected_group4 %>>Gruppe 4</option>
</select>
   <% else %>
<select name="gruppe_select"  playerid="<%= player.id %>"  class="gruppe_select select-option no-scroll alert-warning p-2 rounded  border-0" size="1">
<option value='0' style="background-color:red;" selected>keine Gruppe</option>
<option value='1'>Gruppe 1</option>
<option value='2'>Gruppe 2</option>
<option value='3'>Gruppe 3</option>
<option value='4'>Gruppe 4</option>
</select>


<% end %>

</span>

</td>
<td><%=link_to "edit", "/players/#{player.id}/edit"%>
|
<%= link_to "abmelden", player_path(player), method: :delete, data: { confirm: 'Sicher löschen?'} %>

</td>
</tr>
<% end %>
</table>
<hr />
<%#=link_to "Spieler hinzufügen", "/players/new" %>

</div>
</div>

app/views/players/new.html.erb
<h1>Neuen Spieler hinzufügen</h1>
<%= form_with model: @player  do |f| %>

<%= f.text_field :name, size: "20" %>


  <%= f.submit "hinzufügen" %>
<% end %>

app/views/players/remove_group_from_player.js.erb
//$('#<%= @player.id %>').html("keine Gruppe");
$('#spieler_<%= @player.id %>').remove();
 window.location.href="/players";

app/views/players/show.html.erb
<h1>Spieler show</h1>

<%= @player.id %>
<%= @player.name %>

app/views/players/show_results_in_group.js.erb
//alert("show results in group");
<% [1, 2, 3, 4].each do |grnr| %>
  $('#gr_header_<%= grnr %>').removeClass("gruppeaktiv");
  $('#gr_header_<%= grnr %>').removeClass("bg-light");
  $('#gr_body_<%= grnr %>').removeClass("gruppeaktiv");
  $('#gr_body_<%= grnr %>').removeClass("bg-light");
  $('#btn_einzelergebnisse_<%= grnr %>').removeClass("btn-warning");
  $('#btn_einzelergebnisse_<%= grnr %>').addClass("btn-secondary");
<% end %>
$('#btn_einzelergebnisse_<%= params[:gruppennummer] %>').removeClass('btn-secondary');
$('#btn_einzelergebnisse_<%= params[:gruppennummer] %>').addClass('bg-light');
$('#gr_header_<%= params[:gruppennummer] %>').addClass("bg-light");
$('#gr_body_<%= params[:gruppennummer] %>').addClass("bg-light");
//$('#einzelergebnisse').addClass("gruppeaktiv");
//$('#einzelergebnisse_header').html("<h4>Einzelergebnisse" + " Gruppe <%= params[:gruppennummer] %></h4");
$('#einzelergebnisse').html("");
$('#einzelergebnisse').attr("gruppennummer","<%= params[:gruppennummer] %>");
$('#einzelergebnisse').append("<tr>\
<th>#</th>\
<th>Spieler 1</th>\
<th>Spieler 2</th>\
<th>Satz 1</th>\
<th>Satz 2</th>\
<th>Satz 3</th>\
<th>Satz 4</th>\
<th>Satz 5</th>\
<th>Bälle</th>\
<th>Sätze</th>\
</tr>\
");
<% @matches_in_group_h.each do | key, value | %>
    $('#einzelergebnisse').append("\
    <tr id='einzelergebnisse_tr_<%= key %>' data-matchid='<%= key %>' >\
    ");
        $('#einzelergebnisse_tr_<%= key %>').append("\
        <td><%= key %></td>\
        <td><%= value[0]['player1'] %></td>\
        <td><%= value[0]['player2'] %></td>\
         ");
        $('#einzelergebnisse_tr_<%= key %>').append("\
        <td>\
        <select id='option_results_<%= key %>_set1' data-set='1' data-matchid='<%= key %>' class='ball_select' >\
        ");
        option_results("<%= value[0]['set1'] %>", "<%= key %>", "set1");
        $('#option_results_<%= key %>_set1').append("\
        </select>\
        </td>\
        ");
        $('#einzelergebnisse_tr_<%= key %>').append("\
        <td>\
        <select id='option_results_<%= key %>_set2' data-set='2' data-matchid='<%= key %>' class='ball_select'  >\
        ");
        option_results("<%= value[0]['set2'] %>", "<%= key %>", "set2");
        $('#option_results_<%= key %>_set2').append("\
        </select>\
        </td>\
        ");
        $('#einzelergebnisse_tr_<%= key %>').append("\
        <td>\
        <select id='option_results_<%= key %>_set3' data-set='3' data-matchid='<%= key %>' class='ball_select' >\
        ");
        option_results("<%= value[0]['set3'] %>", "<%= key %>", "set3");
        $('#option_results_<%= key %>_set3').append("\
        </select>\
        </td>\
        ");
        $('#einzelergebnisse_tr_<%= key %>').append("\
        <td>\
        <select id='option_results_<%= key %>_set4' data-set='4' data-matchid='<%= key %>' class='ball_select' <%= value[0]['disabled4'] %> >\
        ");
        option_results("<%= value[0]['set4'] %>", "<%= key %>", "set4");
        $('#option_results_<%= key %>_set4').append("\
        </select>\
        </td>\
        ");
        $('#einzelergebnisse_tr_<%= key %>').append("\
        <td>\
        <select id='option_results_<%= key %>_set5' data-set='5' data-matchid='<%= key %>' class='ball_select' <%= value[0]['disabled5'] %> >\
        ");
        option_results("<%= value[0]['set5'] %>", "<%= key %>", "set5");
        $('#option_results_<%= key %>_set5').append("\
        </select>\
        </td>\
        ");

     

       $('#einzelergebnisse_tr_<%= key %>').append("\
      <td id='ballverhaeltnis_<%= key %>'><%= value[0]['ball_plus'] %>:<%= value[0]['ball_minus'] %></td>\
      ");
       $('#einzelergebnisse_tr_<%= key %>').append("\
      <td id='satzverhaeltnis_<%= key %>'><span id='satzverhaeltnis_<%= key %>_plus'><%= value[0]['satz_plus'] %></span>:<span id='satzverhaeltnis_<%= key %>_plus'><%= value[0]['satz_minus'] %></span></td>\
      ");
    $('#einzelergebnisse').append("\
    </tr>\
    ");

     
     
  
    

<% end %>

$('#einzelergebnisse').append("</table>");



function option_results(punkte, key, setnr) {
  //  console.log(key + '/' + setnr);
    $('#option_results_' + key + '_' + setnr).append("\
        <option>" + punkte + "</option>\
    ");
    $('#option_results_' + key+  '_' + setnr).append("\
            <option> </option>\
            <option>+0</option>\
            <option>+1</option>\
            <option>+2</option>\
            <option>+3</option>\
            <option>+4</option>\
            <option>+5</option>\
            <option>+6</option>\
            <option>+7</option>\
            <option>+8</option>\
            <option>+9</option>\
            <option>+10</option>\
            <option>+11</option>\
            <option>+12</option>\
            <option>+13</option>\
            <option>+14</option>\
            <option>+15</option>\
            <option>+16</option>\
            <option>+17</option>\
            <option>+18</option>\
            <option>-0</option>\
            <option>-1</option>\
            <option>-2</option>\
            <option>-3</option>\
            <option>-4</option>\
            <option>-5</option>\
            <option>-6</option>\
            <option>-7</option>\
            <option>-8</option>\
            <option>-9</option>\
            <option>-10</option>\
            <option>-11</option>\
            <option>-12</option>\
            <option>-13</option>\
            <option>-14</option>\
            <option>-15</option>\
            <option>-16</option>\
            <option>-17</option>\
            <option>-18</option>\
    ");
}

app/views/players/update_set_in_match.js.erb
$('#ballverhaeltnis_<%= params[:matchid] %>').html("<%= @ballverhaeltnis[0] %>:<%= @ballverhaeltnis[1] %>");
$('#satzverhaeltnis_<%= params[:matchid] %>').html("<span id='satzverhaeltnis_<%= params[:matchid] %>_plus'><%= @satzverhaeltnis[0] %></span>:<span id='satzverhaeltnis_<%= params[:matchid] %>_minus'><%= @satzverhaeltnis[1] %></span>");

<% if !@players_in_gruppe_with_results.blank? %>
    console.log("update group results...");
    $('#gruppe_<%= params[:gruppennummer] %>').html();
    $('#gruppe_<%= params[:gruppennummer] %> .tr_spieler').remove();
    <% @players_in_gruppe_with_results.each do | key, value | %>
        $('#gruppe_<%= params[:gruppennummer] %>').append("\
        <tr class='tr_spieler' id='spieler_<%= value[0]['player_id'] %>'>\
        <td><%= value[0]['name'] %></td>\
        <td><%= value[0]['match_plus'] %>:<%= value[0]['match_minus'] %></td>\
        <td><%= value[0]['ball_plus'] %>:<%= value[0]['ball_minus'] %></td>\
        <td><%= value[0]['satz_plus'] %>:<%= value[0]['satz_minus'] %></td>\
        </tr>\
        ");
    <% end %>
<% end %>